---
title: "Visualization"
format: html
editor: visual
---

## How climate affect parasite species richness

I collected data from the litterature. Data includes intestinal parasite and the rain fall and temperature data from the sites where the sample were collected. I calculate the parasite species richness which is the total mumber of parasites a species have.

**Loading data**

```{r}

library(tidyverse)

parasite_data <- read.csv("C:/Users/nurum/Desktop/ordi sumsung/conference/AABA/2024/aaba.csv")
parasite <- read.csv("C:/Users/nurum/Desktop/ordi sumsung/conference/AABA/2024/paranumb.csv")
head(parasite)

```

**Visualization**

```{r}
library(ggplot2)

# Fit linear regression model
fit <- lm(log(frpara) ~ log(temp), data = parasite)

# Create a ggplot object
p <- ggplot(parasite, aes(x = log(temp), y = log(frpara), color = log(rainfall), fill = log(rainfall))) +
  geom_point(shape = 21, size = 3) +
  scale_color_gradient(low = "lightblue", high = "royalblue", name = "log(Rainfall)(mm)") +
  scale_fill_gradient(low = "lightblue", high = "royalblue", name = "log(Rainfall)(mm)") +
  labs(x = "log(Temperature) (C)", y = "log(Parasite Species Richness)", 
       title = "Parasite Species Richness vs. Temperature with Rainfall") +
  theme_minimal() +
  guides(color = guide_colorbar(title = "log(Rainfall)(mm)"), fill = FALSE)  # Remove the fill legend

# Add regression line
p <- p + geom_smooth(method = "lm", se = FALSE, color = "black", formula = y ~ x)

# Show the plot
print(p)


```
